name: Lint and Test

on:
  push:
    branches: [ develop, v2.5, v2.5-unsupported-gcp ]
  pull_request:
    branches: [ develop, v2.5, v2.5-unsupported-gcp ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']

    container:
      image: python:${{ matrix.python-version }}

    services:
      cassandra:
        image: "cassandra:3.11"
      memcached:
        image: "memcached:1.5.6"
      redis:
        image: "redis:4.0.9"
      zookeeper:
        image: "zookeeper:3.4.10"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Update PATH
        run: 'echo "$HOME/.local/bin" >> "$GITHUB_PATH"'

      - name: Install dependencies
        env:
          CASS_DRIVER_NO_EXTENSIONS: theytaketoolongtobuild
        run: |
          pip install pipx
          pipx install poetry==1.8.2
          make .venv

      - name: Lint
        run: |
          make lint

      - name: Test
        run: |
          make test
